import { createHash } from "node:crypto";
import { embed } from "@dstarix/ai-gateway";
import { prisma } from "@dstarix/db";
import { withDatabase } from "./availability";

/**
 * Semantic layer (doc 06 §2): entity embeddings in pgvector. The vector column
 * is an Unsupported Prisma type, so writes/reads go through raw SQL with a
 * text→vector cast. Content-hash gating skips re-embedding unchanged text.
 */

interface EmbeddableEntity {
  id: string;
  name: string;
  tagline: string | null;
  summary: string | null;
}

export function buildEntityEmbeddingText(entity: EmbeddableEntity): string {
  return [entity.name, entity.tagline ?? "", entity.summary ?? ""].join(" ").trim();
}

function vectorLiteral(vector: number[]): string {
  // Only finite numbers reach here (generated by the embedder), so the literal
  // is safe to pass as a text parameter cast to ::vector.
  return `[${vector.map((value) => (Number.isFinite(value) ? value : 0)).join(",")}]`;
}

/** Embed an entity's text and upsert its vector (idempotent on content hash). */
export async function upsertEntityEmbedding(entity: EmbeddableEntity): Promise<void> {
  const text = buildEntityEmbeddingText(entity);
  if (!text) return;
  const contentHash = createHash("sha256").update(text).digest("hex");

  const existing = await prisma.embedding.findUnique({
    where: { subjectKind_subjectId: { subjectKind: "entity", subjectId: entity.id } },
    select: { contentHash: true },
  });
  if (existing?.contentHash === contentHash) return; // unchanged

  const vector = await embed(text);
  const literal = vectorLiteral(vector);

  await prisma.$executeRaw`
    INSERT INTO embeddings (id, subject_kind, subject_id, content_hash, vector, created_at)
    VALUES (gen_random_uuid(), 'entity', ${entity.id}::uuid, ${contentHash}, ${literal}::vector, now())
    ON CONFLICT (subject_kind, subject_id)
    DO UPDATE SET content_hash = EXCLUDED.content_hash, vector = EXCLUDED.vector
  `;
}

export interface SemanticHit {
  id: string;
  similarity: number;
}

/** Nearest published entities to a query by cosine distance. */
export async function semanticEntityIds(query: string, limit: number): Promise<SemanticHit[]> {
  return withDatabase([] as SemanticHit[], async () => {
    const vector = await embed(query);
    const literal = vectorLiteral(vector);
    return prisma.$queryRaw<SemanticHit[]>`
      SELECT e.id, (1 - (em.vector <=> ${literal}::vector))::float8 AS similarity
      FROM embeddings em
      JOIN entities e ON e.id = em.subject_id AND em.subject_kind = 'entity'
      WHERE e.status = 'PUBLISHED' AND e.deleted_at IS NULL
      ORDER BY em.vector <=> ${literal}::vector
      LIMIT ${limit}
    `;
  });
}
